let name = "Anoop Maurya";
console.log(`My name is ${name}`);
console.log(name.length);
console.log(name[2]);
console.log(name[name.length-1]);
let className = 'btn';
className += 'btn-primary';
className += 'none';
console.log(className);
let num = 23;
let strNum = String(num);
console.log(typeof strNum);
console.log(num.toString());